image: maven:3.5.2-jdk-7-alpine

stages:
  - build
  - gitlab-javadoc-page

variables:
  MAVEN_REPO: "$CI_PROJECT_DIR/.m2"

build_artifact:
  stage: build
  script:
    - mvn -Dmaven.repo.local=$MAVEN_REPO package
  artifacts:
    name: "disco-model_$CI_COMMIT_SHA"
    paths:
      - target/*.jar

pages:
  stage: gitlab-javadoc-page
  script:
  - mvn javadoc:javadoc
  - mv target/site/apidocs public
  artifacts:
    paths:
    - public/
